[main]
host="0.0.0.0:8082"

[db]
# driver = "postgres" 
# dsn = "host=localhost port=5432 user=postgres password=postgres dbname=test sslmode=disable"

driver="mysql"
dsn = "root:root@tcp(localhost:3306)/test?charset=utf8&loc=Local"
show_sql = true


[redis]
host = "127.0.0.1:6379"
db = 0
password = ""
trade_log_subscribe_key="list:trade_log"






[kline]
interval=["m1", "d1", "mn"]


