
version: '3'
services:

  mysql:
    image: mysql:5.7
    user: root
    privileged: true
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .data/mysqldata:/var/lib/mysql

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 15432:5432

    volumes:
      - .data/postgresdata:/var/lib/postgresql/data


  redis:
    image: redis
    restart: always
    command: [redis-server]
    ports:
      - 16379:6379


 
